name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v1
    - name: HTTPS Library Build
      run: cd ./https/build && sudo make -B && cd ../../
    
    - uses: actions/checkout@v1
    - name: Link Queue Library Build
      run: cd ./lqueue/build && sudo make -B && cd ../../
    
    - uses: actions/checkout@v1
    - name: Message Queue Library Build
      run: cd ./mqueue/build && sudo make -B && cd ../../ 
    
    - uses: actions/checkout@v1
    - name: Parser Library Build
      run: cd ./parser/build && sudo make -B && cd ../../     